[package]
name = "spirv_parse"
version = "0.1.0"
authors = ["Nanopro <nanopro1g@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "*", features = ['derive']}
serde_json = "*"
lazy_static = "*"
generator = { path = "./generator" }


