#version 450 core

layout(local_size_x = 16, local_size_y = 1, local_size_z = 1) in;


layout(set=0, binding=0) buffer A {
    uint asize;
    float a[];
};
layout(set=0, binding=1) buffer B {
    uint bsize;
    float b[];
};
layout(set=0, binding=2) buffer OutputBuffer { float c[]; };



void main() {
    uint index = gl_GlobalInvocationID.x;

   if (index >= asize){
       return;
   }

    c[index] = a[index] + b[index];

}






